version: 0.0
os: linux
file_exists_behavior: OVERWRITE

files:
  - source: /
    destination: /var/www/my-angular-project

hooks:
  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 60
      runas: root
