spring:
  application:
    name: bookapp

  datasource:
    url: jdbc:h2:file:./bookapp-data
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # ✅ Google OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 420393833930-a8hamfrn9m9ktjfuhe9m86nb6uifbmji.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile